
# libc stdio makefile
LIBC_STDIO_DIR := sysdeps/syscall

MY_OBJS += \
 $(LIBC_STDIO_DIR)/api.o  $(LIBC_STDIO_DIR)/dev.o  $(LIBC_STDIO_DIR)/tty.o\
 $(LIBC_STDIO_DIR)/fs.o  $(LIBC_STDIO_DIR)/open.o  $(LIBC_STDIO_DIR)/signal.o\
$(LIBC_STDIO_DIR)/ctime.o  $(LIBC_STDIO_DIR)/exec.o  $(LIBC_STDIO_DIR)/float.o\
$(LIBC_STDIO_DIR)/libtcc1.o  \
$(LIBC_STDIO_DIR)/longjmp.o  



