


# libc stdio makefile
LIBC_STDIO_DIR := compat/bsd

MY_OBJS += \
    $(LIBC_STDIO_DIR)/bcmp.o  $(LIBC_STDIO_DIR)/bcopy.o\
    $(LIBC_STDIO_DIR)/bzero.o  $(LIBC_STDIO_DIR)/index.o  $(LIBC_STDIO_DIR)/rindex.o

