


# libc stdio makefile
LIBC_DIRENT_DIR := dirent



MY_OBJS += \
$(LIBC_DIRENT_DIR)/alphasort.o\
$(LIBC_DIRENT_DIR)/closedir.o\
$(LIBC_DIRENT_DIR)/opendir.o\
$(LIBC_DIRENT_DIR)/readdir.o\
$(LIBC_DIRENT_DIR)/rewinddir.o\
$(LIBC_DIRENT_DIR)/seekdir.o


CSRC=alphasort.c closedir.c dirfd.c opendir.c readdir.c rewinddir.c scandir.c \
     	seekdir.c telldir.c readdir64.c alphasort64.c scandir64.c readdir_r.c \
	readdir64_r.c

