THIS_SRCS = argz-addsep.o argz-append.o argz-count.o \
	argz-create.o argz-ctsep.o argz-delete.o \
	argz-extract.o argz-insert.o argz-next.o \
	argz-stringify.o


# libc stdio makefile
LIBC_STDIO_DIR := posix/string

MY_OBJS += \
    $(LIBC_STDIO_DIR)/argz-addsep.o \
    $(LIBC_STDIO_DIR)/argz-append.o \
    $(LIBC_STDIO_DIR)/argz-create.o \
    $(LIBC_STDIO_DIR)/argz-ctsep.o \
    $(LIBC_STDIO_DIR)/argz-delete.o \
    $(LIBC_STDIO_DIR)/argz-extract.o \
    $(LIBC_STDIO_DIR)/argz-insert.o \
    $(LIBC_STDIO_DIR)/argz-next.o \
    $(LIBC_STDIO_DIR)/argz-stringify.o \
     $(LIBC_STDIO_DIR)/argz-count.o