



# libc stdio makefile
LIBC_STDIO_DIR := compat/sys

MY_OBJS += \
 $(LIBC_STDIO_DIR)/resource/resource.o  $(LIBC_STDIO_DIR)/resource/gtrlimit.o \
 $(LIBC_STDIO_DIR)/resource/strlimit.o  $(LIBC_STDIO_DIR)/vfs/statfs.o  $(LIBC_STDIO_DIR)/stat/mknod.o

