

# libc stdio makefile
LIBC_STDIO_DIR := compat/unistd

MY_OBJS += \
$(LIBC_STDIO_DIR)/fsync.o  $(LIBC_STDIO_DIR)/ftruncat.o  $(LIBC_STDIO_DIR)/getdtabl.o \
$(LIBC_STDIO_DIR)/gethostn.o  $(LIBC_STDIO_DIR)/getpages.o  $(LIBC_STDIO_DIR)/getwd.o  \
	$(LIBC_STDIO_DIR)/nice.o  $(LIBC_STDIO_DIR)/sync.o  $(LIBC_STDIO_DIR)/truncate.o \
	$(LIBC_STDIO_DIR)/usleep.o  $(LIBC_STDIO_DIR)/vfork.o  $(LIBC_STDIO_DIR)/basename.o\
	$(LIBC_STDIO_DIR)/dirname.o
