




# libc stdio makefile
LIBC_STDIO_DIR := compat/math

MY_OBJS += \
    $(LIBC_STDIO_DIR)/cbrt.o  $(LIBC_STDIO_DIR)/exmp1.o\
    $(LIBC_STDIO_DIR)/exp2.o  $(LIBC_STDIO_DIR)/log10.o \
    $(LIBC_STDIO_DIR)/log2.o  $(LIBC_STDIO_DIR)/sincos.o  $(LIBC_STDIO_DIR)/log1p.o\
    $(LIBC_STDIO_DIR)/powi.o  $(LIBC_STDIO_DIR)/exp10.o

