THIS_SRCS = fnmerge.o fnsplit.o ftreewlk.o \
	ftw.o srchpath.o



# libc stdio makefile
LIBC_DIRENT_DIR := dos/dir

MY_OBJS += \
    $(LIBC_DIRENT_DIR)/fnmerge.o \
    $(LIBC_DIRENT_DIR)/fnsplit.o \
    $(LIBC_DIRENT_DIR)/ftreewlk.o \
    $(LIBC_DIRENT_DIR)/ftw.o \
    $(LIBC_DIRENT_DIR)/srchpath.o 


