

# libc stdio makefile
LIBC_STDIO_DIR := posix/regex

MY_OBJS += \
    $(LIBC_STDIO_DIR)/debug.o \
    $(LIBC_STDIO_DIR)/regcomp.o \    
    $(LIBC_STDIO_DIR)/regexec.o \    
    $(LIBC_STDIO_DIR)/regfree.o \    
    $(LIBC_STDIO_DIR)/split.o \    
    $(LIBC_STDIO_DIR)/regerror


