


# libc stdio makefile
LIBC_BIOS_DIR := sysdeps/bios

MY_OBJS += \
$(LIBC_BIOS_DIR)/biosdisk.o  $(LIBC_BIOS_DIR)/bioscom.o  $(LIBC_BIOS_DIR)/biosequi.o  $(LIBC_BIOS_DIR)/bioskey.o\
$(LIBC_BIOS_DIR)/biosmem.o  $(LIBC_BIOS_DIR)/biosprin.o  $(LIBC_BIOS_DIR)/biostime.o  $(LIBC_BIOS_DIR)/b_time.o\
$(LIBC_BIOS_DIR)/pci.o  $(LIBC_BIOS_DIR)/dos.o  $(LIBC_BIOS_DIR)/disk.o  $(LIBC_BIOS_DIR)/bios_apm.o  $(LIBC_BIOS_DIR)/djgpp.o


