

# libc stdio makefile
LIBC_STDIO_DIR := posix/sys

MY_OBJS += \
    $(LIBC_STDIO_DIR)/waitpid.o \
    $(LIBC_STDIO_DIR)/wait.o  \
     $(LIBC_STDIO_DIR)/chmod.o\
     $(LIBC_STDIO_DIR)/filelen.o \
     $(LIBC_STDIO_DIR)/fixpath.o\
     $(LIBC_STDIO_DIR)/mkfifo.o  \
     $(LIBC_STDIO_DIR)/fstat.o\
     $(LIBC_STDIO_DIR)/mkdir.o \
      $(LIBC_STDIO_DIR)/umask.o\
      $(LIBC_STDIO_DIR)/times.o\
	$(LIBC_STDIO_DIR)/chmod.o  $(LIBC_STDIO_DIR)/filelen.o\
	$(LIBC_STDIO_DIR)/fixpath.o  $(LIBC_STDIO_DIR)/fstat.o  $(LIBC_STDIO_DIR)/mkdir.o \
	$(LIBC_STDIO_DIR)/mkfifo.o \
	$(LIBC_STDIO_DIR)/stat.o  $(LIBC_STDIO_DIR)/umask.o  $(LIBC_STDIO_DIR)/xstat.o

