


# libc stdio makefile
LIBC_STDIO_DIR := ansi/bios

MY_OBJS += \
$(LIBC_STDIO_DIR)/biosdisk.o  $(LIBC_STDIO_DIR)/bioscom.o  $(LIBC_STDIO_DIR)/biosequi.o  $(LIBC_STDIO_DIR)/bioskey.o\
$(LIBC_STDIO_DIR)/biosmem.o  $(LIBC_STDIO_DIR)/biosprin.o  $(LIBC_STDIO_DIR)/biostime.o  $(LIBC_STDIO_DIR)/b_time.o\
$(LIBC_STDIO_DIR)/pci.o  $(LIBC_STDIO_DIR)/dos.o  $(LIBC_STDIO_DIR)/disk.o  $(LIBC_STDIO_DIR)/bios_apm.o  $(LIBC_STDIO_DIR)/djgpp.o


