


# libc stdio makefile
LIBC_STDIO_DIR := posix/unistd/

MY_OBJS += $(LIBC_STDIO_DIR)/access.o  $(LIBC_STDIO_DIR)/alarm.o  $(LIBC_STDIO_DIR)/chdir.o\
$(LIBC_STDIO_DIR)/chown.o  $(LIBC_STDIO_DIR)/close.o  $(LIBC_STDIO_DIR)/ctermid.o\
$(LIBC_STDIO_DIR)/dup2.o \
	 $(LIBC_STDIO_DIR)dup.o  $(LIBC_STDIO_DIR)/execl.o  $(LIBC_STDIO_DIR)/execle.o\
	 $(LIBC_STDIO_DIR)/execlp.o  $(LIBC_STDIO_DIR)/execlpe.o  $(LIBC_STDIO_DIR)/execv.o  \
	 $(LIBC_STDIO_DIR)/execve.o  $(LIBC_STDIO_DIR)/execvp.o \
	 $(LIBC_STDIO_DIR)execvpe.o  $(LIBC_STDIO_DIR)/fork.o\
	 $(LIBC_STDIO_DIR)/getcwd.o  $(LIBC_STDIO_DIR)/getegid.o  $(LIBC_STDIO_DIR)/geteuid.o \
	 $(LIBC_STDIO_DIR)/getgid.o \
	 $(LIBC_STDIO_DIR)getgroup.o  $(LIBC_STDIO_DIR)/getlogin.o  $(LIBC_STDIO_DIR)/getpgrp.o \
	 $(LIBC_STDIO_DIR)/getpid.o  $(LIBC_STDIO_DIR)/getppid.o  $(LIBC_STDIO_DIR)/getuid.o  \
	 $(LIBC_STDIO_DIR)isatty.o  $(LIBC_STDIO_DIR)/link.o  $(LIBC_STDIO_DIR)/lseek.o\
	 $(LIBC_STDIO_DIR)/pause.o \
	 $(LIBC_STDIO_DIR)/pipe.o  $(LIBC_STDIO_DIR)/read.o  $(LIBC_STDIO_DIR)/rmdir.o  $(LIBC_STDIO_DIR)/setgid.o\
	 $(LIBC_STDIO_DIR)setpgid.o  $(LIBC_STDIO_DIR)/setsid.o  $(LIBC_STDIO_DIR)/setuid.o \
	 $(LIBC_STDIO_DIR)/sleep.o  $(LIBC_STDIO_DIR)/ttyname.o  $(LIBC_STDIO_DIR)/unlink.o\
	 $(LIBC_STDIO_DIR)/write.o

