


# libc stdio makefile
LIBC_BIOS_DIR := inet



MY_OBJS += \
$(LIBC_BIOS_DIR)/socketcalls.o\
$(LIBC_BIOS_DIR)/poll.o\
$(LIBC_BIOS_DIR)/resolv.o\
$(LIBC_BIOS_DIR)/addr.o\
$(LIBC_BIOS_DIR)/getservice.o\
$(LIBC_BIOS_DIR)/getproto.o\
$(LIBC_BIOS_DIR)/hostid.o\
$(LIBC_BIOS_DIR)/getnetent.o \
$(LIBC_BIOS_DIR)/getnetbynm.o \
$(LIBC_BIOS_DIR)/getnetbyad.o \
$(LIBC_BIOS_DIR)/inet_net.o \
$(LIBC_BIOS_DIR)/ntop.o\
$(LIBC_BIOS_DIR)/herror.o\
$(LIBC_BIOS_DIR)/if_nametoindex.o \
$(LIBC_BIOS_DIR)/gai_strerror.o \
$(LIBC_BIOS_DIR)/getaddrinfo.o \
$(LIBC_BIOS_DIR)/in6_addr.o \
$(LIBC_BIOS_DIR)/ether_addr.o\
$(LIBC_BIOS_DIR)/ntohl.o

