THIS_SRCS = ctime.o difftime.o strftime.o time.o


# libc stdio makefile
LIBC_STDIO_DIR := ansi/time

MY_OBJS += \
    $(LIBC_STDIO_DIR)/ctime.o $(LIBC_STDIO_DIR)/difftime.o $(LIBC_STDIO_DIR)/strftime.o $(LIBC_STDIO_DIR)/time.o


