

# libc stdio makefile
LIBC_DIRENT_DIR := posix/dirent

MY_OBJS += \
    $(LIBC_DIRENT_DIR)/closedir.o \
    $(LIBC_DIRENT_DIR)/opendir.o \
    $(LIBC_DIRENT_DIR)/readdir.o \
    $(LIBC_DIRENT_DIR)/rewinddi.o \
    $(LIBC_DIRENT_DIR)/seekdir.o \
    $(LIBC_DIRENT_DIR)/telldir.o \
    $(LIBC_DIRENT_DIR)/scandir.o \
    $(LIBC_DIRENT_DIR)/alphasort.o


