
include ../../../Makefile.cfg
include ../../../Makefile.parse

DIR = src/lib/libz/

INCDIR = ./ ../../../../librtl ../../../../libc/include ../../../../posix/include
OBJS += adler32.o compress.o crc32.o gzio.o uncompr.o deflate.o trees.o zutil.o \
        inflate.o infback.o inftrees.o inffast.o

TARGET_O = libz.o

include ../../../Makefile.rules
