
LIBC_POSIX_DIR := posix

# include sub makefiles
include $(addsuffix /Makefile, $(addprefix $(MY_SRCDIR)/$(LIBC_POSIX_DIR)/, \
	fcntl \
	fnmatch \
	grp \
	pwd \
	setjmp \
	stdio \
	sys \
	unistd \
	utime \
	utsname \
	string \
))


