
LIBC_POSIX_DIR := ansi

# include sub makefiles
include $(addsuffix /Makefile, $(addprefix $(MY_SRCDIR)/$(LIBC_POSIX_DIR)/, \
	assert \
	math \
	ctype \
	stdio \
	stdlib \
	bios \
	string \
	locale \
	time \
	posix \
))
