
# libc stdio makefile
LIBC_STDIO_DIR := compat/string/

MY_OBJS += \
$(LIBC_STDIO_DIR)ffs.o  $(LIBC_STDIO_DIR)/memccpy.o  $(LIBC_STDIO_DIR)/stpcpy.o \
$(LIBC_STDIO_DIR)/strcasec.o  $(LIBC_STDIO_DIR)/strdup.o  $(LIBC_STDIO_DIR)/stricmp.o\
	$(LIBC_STDIO_DIR)strlwr.o  $(LIBC_STDIO_DIR)/strncase.o  $(LIBC_STDIO_DIR)/strnicmp.o  \
	$(LIBC_STDIO_DIR)/strsep.o  $(LIBC_STDIO_DIR)/strupr.o  $(LIBC_STDIO_DIR)/memicmp.o


