


# libc stdio makefile
LIBC_MALLOC_DIR := malloc



MY_OBJS += \
$(LIBC_MALLOC_DIR)/realloc.o\
$(LIBC_MALLOC_DIR)/malloc.o\
$(LIBC_MALLOC_DIR)/calloc.o\
$(LIBC_MALLOC_DIR)/free.o\
$(LIBC_MALLOC_DIR)/realloc.o\
$(LIBC_MALLOC_DIR)/memalign.o\
$(LIBC_MALLOC_DIR)/heap_alloc_at.o\
$(LIBC_MALLOC_DIR)/heap_free.o\
$(LIBC_MALLOC_DIR)/heap_alloc.o


CSRC=malloc.c calloc.c free.c realloc.c memalign.c \
	heap_alloc.c heap_alloc_at.c heap_free.c

