
#include $(SDKDIR)/bin/libc/Make.rules
OBJS =  case.o convers.o utf8.o utf16.o



# libc stdio makefile
LIBC_STDIO_DIR := unicode

MY_OBJS += \
    $(LIBC_STDIO_DIR)/case.o \
    $(LIBC_STDIO_DIR)/convers.o \
    $(LIBC_STDIO_DIR)/utf8.o \
    $(LIBC_STDIO_DIR)/utf16.o 



