LIBC_STDIO_DIR := ansi/string


MY_OBJS += \
 $(LIBC_STDIO_DIR)/memchr.o  $(LIBC_STDIO_DIR)/memcmp.o  $(LIBC_STDIO_DIR)/memcpy.o  \
 $(LIBC_STDIO_DIR)/memmove.o  $(LIBC_STDIO_DIR)/memset.o  $(LIBC_STDIO_DIR)/strcat.o \
	$(LIBC_STDIO_DIR)/strchr.o  $(LIBC_STDIO_DIR)/strcmp.o  $(LIBC_STDIO_DIR)/strcoll.o \
	$(LIBC_STDIO_DIR)/strcpy.o  $(LIBC_STDIO_DIR)/strcspn.o  $(LIBC_STDIO_DIR)/strerror.o \
	$(LIBC_STDIO_DIR)/strlen.o  $(LIBC_STDIO_DIR)/strncat.o  $(LIBC_STDIO_DIR)/strncmp.o\
	$(LIBC_STDIO_DIR)/strncpy.o  $(LIBC_STDIO_DIR)/strpbrk.o  $(LIBC_STDIO_DIR)/strrchr.o \
	$(LIBC_STDIO_DIR)/strspn.o  $(LIBC_STDIO_DIR)/strstr.o  $(LIBC_STDIO_DIR)/strtok.o\
	$(LIBC_STDIO_DIR)/strxfrm.o  $(LIBC_STDIO_DIR)/syserr1.o  $(LIBC_STDIO_DIR)/syserr2.o\
	$(LIBC_STDIO_DIR)/syserr3.o


