LIBC_STDIO_DIR := ansi/ctype/

MY_OBJS += \
$(LIBC_STDIO_DIR)/ct_flags.o  $(LIBC_STDIO_DIR)/ct_lower.o  $(LIBC_STDIO_DIR)/ct_upper.o  $(LIBC_STDIO_DIR)/isalnum.o  $(LIBC_STDIO_DIR)/isalpha.o  $(LIBC_STDIO_DIR)/isascii.o  \
	$(LIBC_STDIO_DIR)/iscntrl.o  $(LIBC_STDIO_DIR)/isdigit.o  $(LIBC_STDIO_DIR)/isgraph.o  $(LIBC_STDIO_DIR)/islower.o  $(LIBC_STDIO_DIR)/isprint.o  $(LIBC_STDIO_DIR)/ispunct.o  \
	$(LIBC_STDIO_DIR)/isspace.o  $(LIBC_STDIO_DIR)/isupper.o  $(LIBC_STDIO_DIR)/isxdigit.o  $(LIBC_STDIO_DIR)/toascii.o  $(LIBC_STDIO_DIR)/tolower.o  $(LIBC_STDIO_DIR)/toupper.o


