LIBC_STDIO_DIR := ansi/stdlib


MY_OBJS += \
 $(LIBC_STDIO_DIR)/abort.o  $(LIBC_STDIO_DIR)/abs.o  $(LIBC_STDIO_DIR)/atexit.o \
 $(LIBC_STDIO_DIR)/atof.o  $(LIBC_STDIO_DIR)/atoi.o  $(LIBC_STDIO_DIR)/atol.o  \
 $(LIBC_STDIO_DIR)/atold.o  $(LIBC_STDIO_DIR)/bsearch.o  \
	$(LIBC_STDIO_DIR)/calloc.o  $(LIBC_STDIO_DIR)/div.o  $(LIBC_STDIO_DIR)/exit.o\
	$(LIBC_STDIO_DIR)/labs.o  $(LIBC_STDIO_DIR)/ldiv.o  $(LIBC_STDIO_DIR)/malloc.o\
	$(LIBC_STDIO_DIR)/qsort.o  \
	$(LIBC_STDIO_DIR)/rand.o  $(LIBC_STDIO_DIR)/strtod.o  $(LIBC_STDIO_DIR)/strtol.o \
	$(LIBC_STDIO_DIR)/strtold.o  $(LIBC_STDIO_DIR)/strtoul.o  $(LIBC_STDIO_DIR)/system.o \
	$(LIBC_STDIO_DIR)/strtoll.o  \
	$(LIBC_STDIO_DIR)/strtoull.o  $(LIBC_STDIO_DIR)/llabs.o  $(LIBC_STDIO_DIR)/lldiv.o \
	$(LIBC_STDIO_DIR)/conio.o  $(LIBC_STDIO_DIR)/environ.o  $(LIBC_STDIO_DIR)/errno.o\
	$(LIBC_STDIO_DIR)/getopt.o  $(LIBC_STDIO_DIR)/mouse.o  $(LIBC_STDIO_DIR)/stdlib.o\
	$(LIBC_STDIO_DIR)/getenv.o


