LIBC_STDIO_DIR := ansi/stdio/

MY_OBJS += \
$(LIBC_STDIO_DIR)/readdir.o  $(LIBC_STDIO_DIR)/isatty.o \
$(LIBC_STDIO_DIR)/select.o  $(LIBC_STDIO_DIR)/filelength.o\
$(LIBC_STDIO_DIR)/allocfil.o  $(LIBC_STDIO_DIR)/clearerr.o  $(LIBC_STDIO_DIR)/doprnt.o \
$(LIBC_STDIO_DIR)/doscan.o  $(LIBC_STDIO_DIR)/fclose.o  $(LIBC_STDIO_DIR)/feof.o  \
	$(LIBC_STDIO_DIR)/ferror.o  $(LIBC_STDIO_DIR)/fflush.o  $(LIBC_STDIO_DIR)/fgetc.o \
	$(LIBC_STDIO_DIR)/fgetpos.o  $(LIBC_STDIO_DIR)/fgets.o  $(LIBC_STDIO_DIR)/filbuf.o\
	$(LIBC_STDIO_DIR)/flsbuf.o  \
	$(LIBC_STDIO_DIR)/fopen.o  $(LIBC_STDIO_DIR)/fprintf.o  $(LIBC_STDIO_DIR)/fputc.o\
	$(LIBC_STDIO_DIR)/fputs.o  $(LIBC_STDIO_DIR)/fread.o  $(LIBC_STDIO_DIR)/freopen.o\
	$(LIBC_STDIO_DIR)/frlist.o  \
	$(LIBC_STDIO_DIR)/fscanf.o  $(LIBC_STDIO_DIR)/fseek.o  $(LIBC_STDIO_DIR)/fsetpos.o \
	$(LIBC_STDIO_DIR)/ftell.o  $(LIBC_STDIO_DIR)/fwalk.o  $(LIBC_STDIO_DIR)/fwrite.o \
	$(LIBC_STDIO_DIR)/getc.o  $(LIBC_STDIO_DIR)/getchar.o  \
	$(LIBC_STDIO_DIR)/gets.o  $(LIBC_STDIO_DIR)/getw.o  $(LIBC_STDIO_DIR)/perror.o \
	$(LIBC_STDIO_DIR)/printf.o  $(LIBC_STDIO_DIR)/putc.o  $(LIBC_STDIO_DIR)/putchar.o \
	$(LIBC_STDIO_DIR)/puts.o  $(LIBC_STDIO_DIR)/putw.o \
	$(LIBC_STDIO_DIR)/remove.o  $(LIBC_STDIO_DIR)/_rename.o  $(LIBC_STDIO_DIR)/rename.o \
	$(LIBC_STDIO_DIR)/rewind.o  $(LIBC_STDIO_DIR)/scanf.o  $(LIBC_STDIO_DIR)/setbuf.o\
	$(LIBC_STDIO_DIR)/setbuffe.o  \
	$(LIBC_STDIO_DIR)/setlineb.o  $(LIBC_STDIO_DIR)/setvbuf.o  $(LIBC_STDIO_DIR)/sprintf.o  \
	$(LIBC_STDIO_DIR)/sscanf.o  $(LIBC_STDIO_DIR)/stdaux.o  $(LIBC_STDIO_DIR)/stderr.o \
	$(LIBC_STDIO_DIR)/stdin.o  \
	$(LIBC_STDIO_DIR)/stdiohk.o  $(LIBC_STDIO_DIR)/stdout.o  $(LIBC_STDIO_DIR)/stdprn.o  \
	$(LIBC_STDIO_DIR)/tmpfile.o  $(LIBC_STDIO_DIR)/tmpnam.o  $(LIBC_STDIO_DIR)/ungetc.o  \
	$(LIBC_STDIO_DIR)/vfprintf.o  \
	$(LIBC_STDIO_DIR)/vprintf.o  $(LIBC_STDIO_DIR)/vsprintf.o  $(LIBC_STDIO_DIR)/snprintf.o \
	$(LIBC_STDIO_DIR)/vsnprintf.o  $(LIBC_STDIO_DIR)/uio.o  



