

# libc stdio makefile
LIBC_STDIO_DIR := compat/stdlib/

MY_OBJS += \
$(LIBC_STDIO_DIR)/alloca.o  $(LIBC_STDIO_DIR)/cfree.o  $(LIBC_STDIO_DIR)/getlongp.o \
$(LIBC_STDIO_DIR)/getpass.o  $(LIBC_STDIO_DIR)/itoa.o  $(LIBC_STDIO_DIR)/putenv.o \
	$(LIBC_STDIO_DIR)/random.o  $(LIBC_STDIO_DIR)/swab.o  $(LIBC_STDIO_DIR)/xfree.o \
	$(LIBC_STDIO_DIR)/xmalloc.o  $(LIBC_STDIO_DIR)/xrealloc.o  $(LIBC_STDIO_DIR)/ecvt.o \
	$(LIBC_STDIO_DIR)/ecvtbuf.o  \
	$(LIBC_STDIO_DIR)/fcvt.o  $(LIBC_STDIO_DIR)/fcvtbuf.o  $(LIBC_STDIO_DIR)/gcvt.o \
	$(LIBC_STDIO_DIR)/rand48.o

