
LIBC_POSIX_DIR := compat

# include sub makefiles
include $(addsuffix /Makefile, $(addprefix $(MY_SRCDIR)/$(LIBC_POSIX_DIR)/, \
	bsd \
	io \
	mntent \
	search \
	stdio \
	stdlib \
	string \
	sys \
	time \
	signal \
	termios \
	unistd \
))
