
# libc stdio makefile
LIBC_SUB_DIR := sysdeps/syscall

MY_OBJS += \
 $(LIBC_SUB_DIR)/conio.o\
 $(LIBC_SUB_DIR)/socket.o $(LIBC_SUB_DIR)/strtod.o\
 $(LIBC_SUB_DIR)/pow.o $(LIBC_SUB_DIR)/mbtowc.o

