THIS_SRCS = fdopen.o fileno.o popen.o


# libc stdio makefile
LIBC_STDIO_DIR := posix/stdio

MY_OBJS += \
    $(LIBC_STDIO_DIR)/fdopen.o \
    $(LIBC_STDIO_DIR)/popen.o \
     $(LIBC_STDIO_DIR)/fileno.o

