
# libc stdio makefile
LIBC_SUB3_DIR := sysdeps/images

MY_OBJS += \
	$(LIBC_SUB3_DIR)/huff.o  $(LIBC_SUB3_DIR)/jpeg.o\
	$(LIBC_SUB3_DIR)/main.o  $(LIBC_SUB3_DIR)/vesa.o\
	$(LIBC_SUB3_DIR)/znxml.o  \
	$(LIBC_SUB3_DIR)/gfx.o
