


# libc stdio makefile
LIBC_STDIO_DIR := compat/stdio

MY_OBJS += \
$(LIBC_STDIO_DIR)/mkstemp.o  $(LIBC_STDIO_DIR)/mktemp.o  $(LIBC_STDIO_DIR)/tempnam.o  $(LIBC_STDIO_DIR)/vscanf.o  $(LIBC_STDIO_DIR)/vsscanf.o
