
# libc stdio makefile
LIBC_STDIO_DIR := sysdeps


LIBC_POSIX_DIR := sysdeps
#	thread \

# include sub makefiles
include $(addsuffix /Makefile, $(addprefix $(MY_SRCDIR)/$(LIBC_POSIX_DIR)/, \
	syscall \
))

#	bios \
#	images \
