
LIBC_STDIO_DIR := ansi/math

MY_OBJS += \
$(LIBC_STDIO_DIR)/acosh.o  $(LIBC_STDIO_DIR)/acos.o  $(LIBC_STDIO_DIR)/asinh.o  $(LIBC_STDIO_DIR)/asin.o\
$(LIBC_STDIO_DIR)/atan2.o  $(LIBC_STDIO_DIR)/atanh.o  $(LIBC_STDIO_DIR)/atan.o \
	$(LIBC_STDIO_DIR)/ceil.o  $(LIBC_STDIO_DIR)/cosh.o  $(LIBC_STDIO_DIR)/cos.o \
	$(LIBC_STDIO_DIR)/exp.o  $(LIBC_STDIO_DIR)/fabs.o  $(LIBC_STDIO_DIR)/floor.o  $(LIBC_STDIO_DIR)/fmod.o \
	$(LIBC_STDIO_DIR)/frexp.o  $(LIBC_STDIO_DIR)/huge_val.o  \
	$(LIBC_STDIO_DIR)/hypot.o  $(LIBC_STDIO_DIR)/ldexp.o  $(LIBC_STDIO_DIR)/log.o  $(LIBC_STDIO_DIR)/modfl.o\
	$(LIBC_STDIO_DIR)/modf.o  $(LIBC_STDIO_DIR)/pow10.o  $(LIBC_STDIO_DIR)/pow2.o \
	$(LIBC_STDIO_DIR)/pow.o  $(LIBC_STDIO_DIR)/sinh.o  \
	$(LIBC_STDIO_DIR)/sin.o  $(LIBC_STDIO_DIR)/sqrt.o  $(LIBC_STDIO_DIR)/tanh.o \
	$(LIBC_STDIO_DIR)/tan.o  $(LIBC_STDIO_DIR)/expf.o  $(LIBC_STDIO_DIR)/ldexpf.o \
	$(LIBC_STDIO_DIR)/powf.o  $(LIBC_STDIO_DIR)/logf.o  $(LIBC_STDIO_DIR)/frexpf.o

