
LIBC_STDIO_DIR := ansi/locale

MY_OBJS += \
  $(LIBC_STDIO_DIR)/lconv.o  $(LIBC_STDIO_DIR)/mbcurmax.o  $(LIBC_STDIO_DIR)/mblen.o\
 $(LIBC_STDIO_DIR)/mbstowcs.o  $(LIBC_STDIO_DIR)/mbtowc.o  $(LIBC_STDIO_DIR)/setlocal.o \
$(LIBC_STDIO_DIR)/wcstombs.o  $(LIBC_STDIO_DIR)/wctomb.o

